### ISSUE TITLE
Textfield content translated when google translator enabled on Chrome

### ISSUE THREAD

**Issue by guirak** [JPro-one/JPro-tickets#160]
Hi Florian, 

I create here the ticket of our discussion.

Reproduction : 
- Open the JPRO APP with Chrome 
- Enable the translator (for example english -> french)
=> The labels are translated : OK
- Write a word that exists in english in a textfield
=> The word is translated too : NOK

Regards,

**Comment by guirak** [comment]
Hi Florian, 

Have you found any solution for this problem ? This is very problematic for new users that start using our software. 
They don't understand the problem and stop using it when it happens.

Thank you

**Comment by guirak** [comment]
Hi Florian, 

I have just tested the 2023.2.2 release and it solved the translation problem on TextField content. Thank you.

For now, I have some texts in simple label that must not be translated too. 

For example I'm using KeyboardFX and the Keyboard is still translated as the text is on a Label or Button.

![Screenshot_20230818-142344_Chrome](https://github.com/JPro-one/JPro-tickets/assets/93905646/27275d87-78e5-439a-b95f-0102a5c2dba6)

Maybe it will be possible to extends the mechanism you have used for textfields to other nodes but only in demand ? 
For example, if a node contains a "no-translate" style class, the translation would be disabled for the texts on the node and childs node.

I don't know if it is something easy to do but if it's possible it will be perfect.

Thank you,

**Comment by FlorianKirmaier** [comment]
Hi Guirak!

I just wanted to tell you that we've implemented it in the latest Version.

Your suggestion is correct! We need a way to dynamically enable/disable translation - based on the logic of the application.
We will add this feature in the next update!

**Comment by guirak** [comment]
Hi Florian, 

Yes, my screenshot is with the last version (2023.2.2). 

The problem is solved for TextFields. But in my case, it still a problem for the KeyboardFX.

Thank you.

**Comment by besidev** [comment]
Hi Guirak!

We just released version `2023.3.0-M1`. We now provide a way to enable/disable translation on a specific node. 
As an example, disabling translation on a specific text field can be done by calling `node.getProperties().put("translate", false);`. The translation rule is inherited from the parent node. Please give it a try and let us know your opinion on this new implementation.

**Comment by guirak** [comment]
Hi besidev, I have just tested. It's working perfectly. 

The implementation is good for me too. For the moment, I am not interesting in providing an automatic translation so I will just put the property to the root node  of the scene.

Thank you.

**Comment by besidev** [comment]
Hi Guirak,

We are glad its working perfectly as expected. Thank you for your quick feedback.
