### ISSUE TITLE
WebApi.openStageAsTab issues

### ISSUE THREAD

**Issue by Hugolarson** [JPro-one/JPro-tickets#58]
Two  issues below:

1:
getScene().getWindow().hide() throws this exception

```
java.lang.NullPointerException: null
        at simplefx.util.ReflectionUtil$UseReflection.applyDynamic(ReflectionUtil.scala:18)
        at com.jpro.meta.tk.UtilSceneTKListener$ExtendView.view(UtilSceneTKListener.scala:24)
        at com.jpro.meta.tk.UtilSceneTKListener$ExtendView.isMonocle(UtilSceneTKListener.scala:25)
        at com.jpro.meta.tk.SceneInputListener.processInputInScene(SceneInputListener.scala:127)
        at com.jpro.meta.tk.SceneInputListener.processInput(SceneInputListener.scala:117)
        at com.jpro.meta.tk.SceneInputListener.processInputs(SceneInputListener.scala:98)
        at com.jpro.meta.tk.SceneInputListener.$anonfun$new$4(SceneInputListener.scala:39)
        at simplefx.cores.standard.parts.CoreTimeEvent.$anonfun$runAsAnimation$1(CoreTimeEvent.scala:64)
        at simplefx.cores.standard.parts.CoreTimeEvent$$anon$2.handle(CoreTimeEvent.scala:46)
        at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$0(AnimationTimer.java:57)
```
2:
Event only called once when stage first shown. After that event does not work.
stage.focusedProperty().addListener((observable, oldValue, newValue) -> {
			System.out.println(" focus "+observable+" o "+oldValue+" "+newValue);
		});

**Comment by FlorianKirmaier** [comment]
both Stage.hide() and Stage.isFocused() don't realy have a meaning when using JPro.
The Exception looks like the Scene is missing. I also can't see the method hide() in the stacktrace.
I also cannot reproduce the exception. Please provide a full application when you need further help.

**Comment by Hugolarson** [comment]
This is the full exception. Rest is swallowed somehow making it difficult to debug because it does not show where in my code it's thrown. This apply also to the other exception with MaskerPane. No reference to my code with line number.

Can you maybe make a built with better trace information?

**Comment by FlorianKirmaier** [comment]
According to the exception, i probably cannot do more as adding information like "The peer of the scene is not available" which probably won't help you.
Can you provide me with a minimal application that creates the mentioned exception? Then I can probably fix the problem or provide a deeper explanation about the problem.

**Comment by Hugolarson** [comment]
Find attached eclipse project.

[JproTest.zip](https://github.com/JPro-one/JPro-tickets/files/4796352/JproTest.zip)

**Comment by FlorianKirmaier** [comment]
Thank you for the test class. With the test class I was able to the new stack trace and fix the cause.
It should work now with the latest version of 2019.2.5-SNAPSHOT

**Comment by Hugolarson** [comment]
2019.2.5-SNAPSHOT is the one you made yesterday. Is new same build number?

Anyway it still does not work. No exception but also stage does not open with maskerpane.

**Comment by FlorianKirmaier** [comment]
Hm, it's required that show is called also in the JPro case. It should probably be changed to either call show automatically or throw an exception with this information.

**Comment by Hugolarson** [comment]
Funny that stage is shown without calling show() without maskerpane but with maskerpane show() is needed.

Now **another** issue!
If you show a new stage from stage shown with .openStageAsTab(stage) funny things happen.
A new tab is not opened UNTILL one close the current tab!

Try my test project.

press "open tab stage"
press "another stage" -> nothing happen.
press "another stage" again -> nothing happen.

Now close the current tab and suddenly the stages are shown!
Tried with Chrome and Edge.
openStageAsPopup seems to work.

[JproTest.zip](https://github.com/JPro-one/JPro-tickets/files/4802425/JproTest.zip)

**Comment by FlorianKirmaier** [comment]
@Hugolarson
I wasn't able to reproduce the problem, but browsers generally don't like it, when new tabs and popups are created "dynamically by code". In general, in the web one has to do a click to open a new tab, otherwise the browser might consider the action as spam.
The "openStageAsTab" method probably only work reliable when it is not invoked to often.
It would probably be possible to add something like "openStageOnClick".
In general, I would recommend implementing as popups based on StackPane. 
checkout out popup sample: https://github.com/JPro-one/JPro-Samples

We've also made a small "Web framework" (It also works on Desktop and mobile) to allow writing Route based applications with JavaFX.
Framework: https://github.com/Sandec/jpro-web
Sample: https://github.com/JPro-one/JPro-Samples
This framework uses classic "Links" which work reliably in the browser. The links are also indexed and followed by Google.
Our website www.jpro.one is using this framework and basically all our JavaFX projects.

**Comment by Hugolarson** [comment]
I put my test project on http://35.228.44.205/

Don't think it's about browser might think it spam and block. Browser indeed can block popups which blocks the tab but its possible to let browser accept popups from certain sites.

There is a problem in webapi with openStageAsTab when used in a "openStageAsTab" tab with Chromium browsers.
**Everything works fine in Firefox!**

Please visit link http://35.228.44.205/ with Chrome
1. Click"Open tab stage"
2. Click "Another stage" three times. (nothing happens)
3. Close current (2) browser tab with the "x".  BOOM (all stages in 2. are suddenly shown!)

openStageAsTab is a very nice way to emulate a independent application Dialogs/Frames.

**Comment by FlorianKirmaier** [comment]
Now I get the problem.
For each stage you need a different instance of the WebAPI.
After creating the second Stage, you have to call "WebAPI.getWebAPI(stage)" and call the "openStageAsTab()" of the new instance.
Previously, the tab in the background tried to open a new tab, which is suspicious because why should an inactive tab create new tabs? Browser blocks this because this can be misused. But your sample should work properly if the just call getWebAPI with the new stage.

**Comment by Hugolarson** [comment]
I think it's already according your suggestion.
The new instance stage is called with new WebAPI.getWebAPI(stageMain)

`public class FxMain extends JProApplication{
	
	static Stage stageMain;
	
	MaskerPane masker = new MaskerPane();
	
	@Override
	public void start (Stage stage) throws Exception {
		stageMain = stage;
		
		Label lbl = new Label("label");
        TextField tf = new TextField();
        
        Button b = new Button("open tab stage");
        b.setOnAction(e -> showStage());
        
        VBox box = new VBox(tf, lbl, b);
        
        masker.setVisible(false);
        javafx.scene.layout.StackPane stackpane = new javafx.scene.layout.StackPane(box, masker);
        
        Scene scene = new Scene(stackpane);

        stage.setScene(scene);
        stage.setTitle("FX");
        stage.setWidth(1000);
        stage.setHeight(500);
        
        stage.show();
	}
	private static void showStage() {
		BorderPane pane = new BorderPane();
		MaskerPane masker = new MaskerPane();
		
		Stage stage = new Stage();
		
		Button b = new Button("Another stage");
		b.setOnAction(e -> showStage());
		Label lbl = new Label("hello sub stage");
		pane.setTop(b);
		pane.setCenter(lbl);
		javafx.scene.layout.StackPane stackpane = new javafx.scene.layout.StackPane(pane, masker);
		Scene scene = new Scene(stackpane, 300, 300);
		stage.setScene(scene);
		
		masker.setVisible(false);
		
		stage.show();
		
		if(WebAPI.isBrowser()) {
			WebAPI.getWebAPI(stageMain).openStageAsTab(stage);
		}
	}
	public static void main (String[] args) {
	     launch (args);
	}
}`

**Comment by FlorianKirmaier** [comment]
No, it's not. The WebAPI of the focused stage must be used.
You should give "showStage" the WebAPI or the current Stage as an argument.
You should also remove the static stageMain. A static of the type Stage or WebAPI is basically a guarantee for a bug somewhere in the application.

**Comment by Hugolarson** [comment]
Now I understand how to use it.
Thank you!
