### ISSUE TITLE
PathElement.absolute = false is not supported

### ISSUE THREAD

**Issue by SchweinchenFuntik** [JPro-one/JPro-tickets#83]
Why are they not supported? Will it ever be supported?

**Comment by FlorianKirmaier** [comment]
What do you mean by relative paths?
Can you be a bit more specific?

**Comment by SchweinchenFuntik** [comment]
Sorry. I use Path with absolute = false, and I get a message in the logs: Relative paths are not supported!

Application view is incorrect.
I wonder why this function is not supported

**Comment by FlorianKirmaier** [comment]
Hm, interesting, totally forgot about that.
It's probably the least used feature in JavaFX, never got a complaint about it.
It wasn't supported, because of a strange JavaFX bug which we would have to reinvestigate.
it's most likely possible to support.

**Comment by SchweinchenFuntik** [comment]
Another question, is it worth waiting for the correction?

**Comment by FlorianKirmaier** [comment]
That's a good question.
If you can wait for about 2 weeks, we should be able to give you a build with a fix.

**Comment by SchweinchenFuntik** [comment]
Thank. So far made a layout with `absolute = true`

**Comment by mipastgt** [comment]
Is that issue fixed by now?

**Comment by FlorianKirmaier** [comment]
No, it's not fixed yet. 
If it's relevant for you, we will prioritize it, 
otherwise, we will first do other features.

**Comment by mipastgt** [comment]
It would be nice to have to define symbols placed along a path. With relative coordinates you can reuse the path elements and place them with a single moveto. But I do not currently have an urgent need for it as long as it is not forgotten :-)
